server:
  port: 8080

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/basic
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: {Passowrd}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  thymeleaf:
    cache: false

  redis:
    host: localhost
    port: 6379

  session:
    store-type: redis

logging:
  level:
    org.hibernate.SQL: debug
